global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'eve-sde-monitor'

scrape_configs:
  - job_name: 'eve-sde-server'
    static_configs:
      - targets: ['eve-sde-server:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
